#!/bin/bash

# @file cosm-lookup
#
# Cosmos Project
# Config directory cascade utility
# current version: 2020-01-09rh
# first version: 2019-05-24rh
#
# From the working directory, queries each config directory up the tree for a matching subpath.
#
# e.g.
#
#     $ cosm-lookup sub/path/target.x
#     /home/thisguy/.config/sub/path/target.x
#
# if no args, find the first config directory in or above PWD.
#



#### Setup ####

CONFNAME_RE=[._][Cc]osm

shopt -s dotglob



#### FUNCTIONS ####

function print_usage ()
{
    echo "usage: $0 [SUBPATH]" >&2
}


#### MAIN ####

if [ -n "$2" ]
then
    print_usage
    exit -1
fi


if [ -n "$1" ]
then
    subpath="$1"
else
    subpath=""
fi


dir="$PWD"

if [ ! -e "$dir" ]
then
    echo "$0: err: working dir invalid" >&2
    exit -1
fi

while [ "$dir" != "/" ]
do
    target=$(echo "$dir"/$CONFNAME_RE/"$subpath")

    if [ -e "$target" ]
    then
        echo $target
        exit
    fi

    dir=`dirname "$dir"`
done







